columnSuffix: null
contentColumnType: text
fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb # Common
handle: caption
instructions: ''
name: Caption
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
